services:
  chess-rl:
    build: .
    container_name: birds-lmannini-e3da-3
    environment:
      - PYTHONPATH=/app
      - TORCH_BACKENDS_CUDNN_BENCHMARK=true
      - STOCKFISH_PATH=/usr/games/stockfish
    volumes:
      - ./logs:/app/logs
      - ./results:/app/results
    ports:
      - "6006:6006"  # TensorBoard
      - "8888:8888"  # Jupyter (optional)
    command: python train_hydra.py
    stdin_open: true
    tty: true 