services:
  backend:
    build: .
    volumes:
      - ./models:/app/models
    environment:
      - STOCKFISH_PATH=/usr/games/stockfish
    ports:
      - "8000:8000"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend 