# @package _global_
agent:
  name: default
  buffer_size: 200000
  min_buffer_size: 10000
  batch_size: 64
  learning_rate: 1e-4
  gamma: 0.99
  tau: 0.005
  replay_type: standard  # standard or prioritized
