# @package _global_
# GNN MultiScale: Architettura multi-scala innovativa

model:
  _target_: src.models.gnn_dqn.GNNDQN
  config:
    _target_: src.models.gnn_dqn.GNNDQNConfig
    
    # Enhanced graph construction
    graph_config:
      _target_: src.utils.chess_graph.ChessGraphConfig
      include_empty_squares: true
      max_spatial_distance: 3
      include_mobility_edges: true
      include_tactical_edges: true
      normalize_features: true
    
    # Multi-scale architecture
    node_input_dim: 24
    edge_input_dim: 8
    hidden_dim: 384     # Balanced for multi-scale
    num_gnn_layers: 6
    gnn_type: 'multiscale'  # Multi-scale processing
    
    # Advanced options
    use_residual_blocks: true
    use_multiscale: true
    multiscale_scales: ['local', 'tactical', 'strategic']
    
    # Attention settings
    num_attention_heads: 12
    attention_dropout: 0.1
    
    # Pooling
    pooling_types: ['attention', 'strategic']
    num_pooling_heads: 6
    
    # Output
    action_size: 4672
    dueling: true
    
    # Regularization
    dropout: 0.15
    layer_norm: true
    
    # Positional encoding
    use_positional_encoding: true
