# @package _global_
# GNN-Pro A40: Ottimizzato per GPU A40 (48GB VRAM) - Target ELO 800-1200

model:
  _target_: src.models.gnn_dqn.GNNDQN
  config:
    _target_: src.models.gnn_dqn.GNNDQNConfig
    
    # Enhanced graph construction
    graph_config:
      _target_: src.utils.chess_graph.ChessGraphConfig
      include_empty_squares: true
      max_spatial_distance: 3  # Larger context
      include_mobility_edges: true
      include_tactical_edges: true
      normalize_features: true
    
    # A40-Optimized architecture (48GB VRAM)
    node_input_dim: 24  # Enhanced node features
    edge_input_dim: 8   # Enhanced edge features
    hidden_dim: 512     # Large hidden dimension for A40
    num_gnn_layers: 8   # Deep network for better performance
    gnn_type: 'resgateau'  # Best architecture
    
    # Advanced options
    use_residual_blocks: true
    use_multiscale: false
    
    # Multi-head attention
    num_attention_heads: 16  # More heads for better attention
    attention_dropout: 0.1
    
    # Advanced pooling
    pooling_types: ['attention', 'hierarchical', 'strategic']
    num_pooling_heads: 8
    
    # Output
    action_size: 4672
    dueling: true
    
    # Regularization (less dropout for larger model)
    dropout: 0.1
    layer_norm: true
    
    # Positional encoding
    use_positional_encoding: true
