# @package _global_
# Large GNN-DQN configuration for production

model:
  _target_: src.models.gnn_dqn.GNNDQN
  config:
    _target_: src.models.gnn_dqn.GNNDQNConfig
    
    # Graph construction
    graph_config:
      _target_: src.utils.chess_graph.ChessGraphConfig
      include_empty_squares: true
      max_spatial_distance: 3  # Larger spatial context
      include_mobility_edges: true
      include_tactical_edges: true
      normalize_features: true
    
    # Model architecture
    node_input_dim: 16
    edge_input_dim: 4
    hidden_dim: 512
    num_gnn_layers: 6
    gnn_type: 'hybrid'  # Best of both worlds
    
    # GAT specific
    num_attention_heads: 16
    attention_dropout: 0.1
    
    # GINE specific
    gine_eps: 0.05  # Smaller epsilon for more stability
    train_eps: true
    
    # Pooling
    pooling_types: ['mean', 'max', 'attention']
    
    # Output
    action_size: 4672
    dueling: true
    
    # Regularization
    dropout: 0.1  # Less dropout for larger model
    layer_norm: true
    
    # Positional encoding
    use_positional_encoding: true
