# @package _global_
# Medium GNN-DQN configuration for development

model:
  _target_: src.models.gnn_dqn.GNNDQN
  config:
    _target_: src.models.gnn_dqn.GNNDQNConfig
    
    # Graph construction
    graph_config:
      _target_: src.utils.chess_graph.ChessGraphConfig
      include_empty_squares: true
      max_spatial_distance: 2
      include_mobility_edges: true
      include_tactical_edges: true  # Enable tactical edges
      normalize_features: true
    
    # Model architecture
    node_input_dim: 16
    edge_input_dim: 4
    hidden_dim: 256
    num_gnn_layers: 4
    gnn_type: 'hybrid'  # Use hybrid GAT+GINE
    
    # GAT specific
    num_attention_heads: 8
    attention_dropout: 0.1
    
    # GINE specific
    gine_eps: 0.1
    train_eps: true
    
    # Pooling
    pooling_types: ['mean', 'max', 'attention']  # Full pooling
    
    # Output
    action_size: 4672
    dueling: true
    
    # Regularization
    dropout: 0.2
    layer_norm: true
    
    # Positional encoding
    use_positional_encoding: true
