# @package _global_
training:
  name: production
  max_moves: 100
  game_timeout: 60.0
  games_per_episode: 20
  training_frequency: 10
  target_update_frequency: 100
  eval_frequency: 100
  eval_games: 20
  stockfish_depth: 1
  stockfish_time: 0.2
  log_frequency: 20
  checkpoint_frequency: 200
